version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    command: gunicorn Bclub.wsgi -b 0.0.0.0:8000
    environment:
    - ENVIRONMENT=development
    - DEBUG=1
    volumes:
    - .:/code
    - media:/src/media/
    - static:/src/static/
    ports:
    - 8000:8000
    depends_on:
    - db
  
volumes:
  postgres_data:
  media:
  static:
